"""Suggestions endpoint — POST /v1/suggestions.

Returns 4 contextual follow-up prompts the user might want to ask next,
generated by a lightweight LLM call (no tools, no agent graph overhead).

Input: the last user message + the last assistant reply.
Output: [{id, label, prompt}] — ready to render as chips in the chat UI.
"""

from __future__ import annotations

import hmac
import json
import re

from fastapi import APIRouter, HTTPException, Request, status
from langchain_core.messages import HumanMessage, SystemMessage
from pydantic import BaseModel

from ai_service.agents.pm_agent import build_llm
from ai_service.config import get_settings
from ai_service.logging import get_logger

logger = get_logger(__name__)
router = APIRouter(prefix="/v1", tags=["suggestions"])

_SYSTEM_PROMPT = """\
You are a helpful assistant for a project management tool called Planiqo.

Given the last exchange in a PM chat session, generate exactly 4 short follow-up questions the user would naturally want to ask next. The questions should be:
- Directly related to what was just discussed (sprint, issues, blockers, team, backlog, etc.)
- Specific and actionable, not generic
- Varied — cover different angles (drill-down, action, comparison, status)

Respond ONLY with a valid JSON array, no markdown, no explanation:
[
  {"id": "s1", "label": "<6 words max>", "prompt": "<full question under 60 words>"},
  {"id": "s2", "label": "...", "prompt": "..."},
  {"id": "s3", "label": "...", "prompt": "..."},
  {"id": "s4", "label": "...", "prompt": "..."}
]
"""

_JSON_RE = re.compile(r"\[.*\]", re.DOTALL)


class SuggestionRequest(BaseModel):
    user_message:      str
    assistant_message: str


class SuggestionItem(BaseModel):
    id:     str
    label:  str
    prompt: str


class SuggestionsResponse(BaseModel):
    suggestions: list[SuggestionItem]


def _verify_token(request: Request) -> None:
    expected = getattr(request.app.state, "service_token", "") or ""
    if not expected:
        return
    presented = request.headers.get("x-service-token", "")
    if not hmac.compare_digest(presented, expected):
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid service token.")


@router.post(
    "/suggestions",
    response_model=SuggestionsResponse,
    status_code=status.HTTP_200_OK,
    summary="Generate contextual follow-up suggestions",
)
async def get_suggestions(request: Request, body: SuggestionRequest) -> SuggestionsResponse:
    _verify_token(request)

    settings = get_settings()
    if not settings.llm_configured:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="LLM not configured.",
        )

    llm = build_llm(settings)

    user_content = (
        f"User asked: {body.user_message}\n\n"
        f"Assistant replied: {body.assistant_message}"
    )

    try:
        response = await llm.ainvoke([
            SystemMessage(content=_SYSTEM_PROMPT),
            HumanMessage(content=user_content),
        ])
        raw = str(response.content).strip()

        # Extract JSON array even if model wraps it in markdown
        match = _JSON_RE.search(raw)
        if not match:
            raise ValueError("No JSON array in response")

        items = json.loads(match.group())
        suggestions = [
            SuggestionItem(
                id=f"s{i+1}",
                label=str(item.get("label", "")),
                prompt=str(item.get("prompt", "")),
            )
            for i, item in enumerate(items[:4])
            if item.get("label") and item.get("prompt")
        ]
        return SuggestionsResponse(suggestions=suggestions)

    except Exception as exc:
        logger.warning("suggestions.llm_failed", extra={"error": str(exc)})
        # Return empty — the frontend falls back to template suggestions gracefully
        return SuggestionsResponse(suggestions=[])
